<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>01a4618e-0cf0-4087-b95f-4b19870f6aa6</elementGuidId>
   <imagePath>Screenshots/Targets/input_Username_username.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt-username-broken</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/input_Username_username.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
